"""
Central configuration for ML training and evaluation.

Eye Hear U uses a video classifier (Approach B): a 3D CNN backbone
(e.g., I3D or SlowFast pretrained on Kinetics-400) fine-tuned on
short ASL sign clips.

The vocabulary is NOT limited to a small scenario set — it covers
the full gloss vocabulary present in ASL Citizen (~2,731 classes),
supplemented by WLASL and MS-ASL.
"""

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class DataConfig:
    """Dataset and preprocessing configuration."""

    # Paths (relative to ml/)
    processed_data_dir: Path = Path("../data/processed")

    # The number of classes is determined at runtime by label_map.json,
    # which is generated by the data pipeline (build_unified_dataset.py).
    # The value below is a reasonable default based on ASL Citizen's
    # vocabulary after filtering rare glosses.
    num_classes: int = 2000

    # Video clip properties (must match preprocess_clips.py settings)
    num_frames: int = 16        # frames uniformly sampled per clip
    frame_height: int = 224
    frame_width: int = 224

    # DataLoader
    num_workers: int = 4


@dataclass
class ModelConfig:
    """Model architecture configuration."""

    # Video backbone — pretrained on Kinetics-400
    backbone: str = "i3d_r50"       # "i3d_r50", "slowfast_r50", "r3d_18"
    pretrained: bool = True
    backbone_freeze_epochs: int = 3  # freeze backbone for first N epochs

    # Classification head
    head_dropout: float = 0.5


@dataclass
class TrainConfig:
    """Training hyperparameters."""

    batch_size: int = 8             # smaller than image training due to video memory
    learning_rate: float = 1e-3
    weight_decay: float = 1e-4
    epochs: int = 30
    early_stopping_patience: int = 5

    # Scheduler
    scheduler: str = "cosine"
    warmup_epochs: int = 2

    # Checkpointing
    checkpoint_dir: Path = Path("checkpoints")
    save_every_n_epochs: int = 5

    # Device
    device: str = "mps"             # "cpu", "cuda", or "mps" (Apple Silicon)

    # Logging
    use_wandb: bool = False
    wandb_project: str = "eye-hear-u"


@dataclass
class Config:
    data: DataConfig = field(default_factory=DataConfig)
    model: ModelConfig = field(default_factory=ModelConfig)
    train: TrainConfig = field(default_factory=TrainConfig)
