#!/usr/bin/env python3
"""Build PR comment + README snippet from CI coverage artifacts."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path


def parse_py_total_pct(report_path: Path) -> str:
    text = report_path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        if line.strip().startswith("TOTAL"):
            parts = line.split()
            return parts[-1] if parts else "?"
    return "?"


def parse_mobile_summary(summary_path: Path) -> tuple[str, str]:
    data = json.loads(summary_path.read_text(encoding="utf-8"))
    total = data.get("total") or {}
    lines = total.get("lines") or {}
    funcs = total.get("functions") or {}
    lp = lines.get("pct")
    fp = funcs.get("pct")
    return (
        f"{lp}%" if isinstance(lp, (int, float)) else "?",
        f"{fp}%" if isinstance(fp, (int, float)) else "?",
    )


def main() -> int:
    if len(sys.argv) < 6:
        print(
            "usage: build_coverage_report.py <backend_report.txt> <ml_report.txt> "
            "<mobile_coverage_summary.json> <comment_out.md> <readme_snippet_out.md> "
            "[run_url]",
            file=sys.stderr,
        )
        return 2

    backend_p = Path(sys.argv[1])
    ml_p = Path(sys.argv[2])
    mobile_p = Path(sys.argv[3])
    comment_out = Path(sys.argv[4])
    snippet_out = Path(sys.argv[5])
    run_url = sys.argv[6] if len(sys.argv) > 6 else ""

    backend_cov = parse_py_total_pct(backend_p)
    ml_cov = parse_py_total_pct(ml_p)
    mob_l, mob_f = parse_mobile_summary(mobile_p)

    run_link = f"[this workflow run]({run_url})" if run_url else "the latest workflow run"

    comment = f"""## Test coverage

| Component | Coverage |
|-----------|----------|
| **Backend** (`app/`) | **{backend_cov}** (line + branch, pytest-cov) |
| **ML** | **{ml_cov}** (line, pytest-cov) |
| **Mobile** | **{mob_l}** lines, **{mob_f}** functions (Jest) |

CI fails if backend or ML drops below **100%** or if mobile goes below Jest `coverageThreshold`.

_Generated by GitHub Actions — {run_link}._
"""

    snippet = f"""**Test coverage (CI):** Backend **{backend_cov}** · ML **{ml_cov}** · Mobile **{mob_l}** lines / **{mob_f}** functions — see {run_link}."""

    comment_out.write_text(comment.strip() + "\n", encoding="utf-8")
    snippet_out.write_text(snippet.strip() + "\n", encoding="utf-8")

    if len(sys.argv) > 7:
        readme_path = Path(sys.argv[7])
        readme = readme_path.read_text(encoding="utf-8")
        snip = snippet_out.read_text(encoding="utf-8").strip()
        block = f"<!-- COVERAGE_REPORT_START -->\n{snip}\n<!-- COVERAGE_REPORT_END -->"
        pat = re.compile(
            r"<!-- COVERAGE_REPORT_START -->.*?<!-- COVERAGE_REPORT_END -->",
            re.DOTALL,
        )
        if not pat.search(readme):
            print("README: missing COVERAGE_REPORT markers", file=sys.stderr)
            return 1
        readme_path.write_text(pat.sub(block, readme, count=1), encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
