apiVersion: v1
kind: Service
metadata:
  name: eyehearu-api
  namespace: eyehearu
  labels:
    app: eyehearu-api
spec:
  type: ClusterIP
  selector:
    app: eyehearu-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
